FROM public.ecr.aws/lambda/python:3.13
RUN dnf install -y git && dnf clean all
COPY dependencies.txt ${LAMBDA_TASK_ROOT}/dependencies.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/dependencies.txt
COPY src ${LAMBDA_TASK_ROOT}/src

ENV PYTHONPATH=${LAMBDA_TASK_ROOT}/src \
    RATE_LOG_LEVEL=INFO

CMD ["enqueue_rate.handler"]
